/* Generated by `obscene-tool self-header` from selfish::container::table.
 * Do not edit by hand. */

#ifndef OBSCENE_SELF_HEADER_GEN_H
#define OBSCENE_SELF_HEADER_GEN_H

/* Layout of a container field the self-audit check confirms. */
typedef struct {
    const char *field;
    unsigned int offset;
    unsigned int size;
    unsigned long long expected;
} obs_self_field;

/* Fixed fields identical across both console generations. */
static const obs_self_field obs_self_fields[] = {
    {"version", 0x04, 1, 0x0ull},      {"mode", 0x05, 1, 0x1ull},
    {"endian", 0x06, 1, 0x1ull},       {"attributes", 0x07, 1, 0x12ull},
    {"key_type", 0x08, 4, 0x101ull},   {"category", 0x08, 1, 0x1ull},
    {"program_type", 0x09, 1, 0x1ull}, {"flags", 0x1a, 2, 0x22ull},
    {"padding3", 0x1c, 4, 0x0ull},
};

/* Container magics (LE word at offset 0), both generations, for recognising a SELF. */
static const unsigned long long obs_self_magics[] = {
    0xeef51454ull, /* current generation */
    0x1d3d154full, /* previous generation */
};

#endif /* OBSCENE_SELF_HEADER_GEN_H */
