//! The index at the top of `docs/DECISIONS.md`.
//!
//! `CLAUDE.md` says to read the decision log at the start of every working session, and the
//! log is 155 entries over five thousand lines. Nobody reads that; they grep it, which works
//! only if you already know the word - and the entries most worth finding are the ones you
//! do not yet know exist.
//!
//! That is the failure this fixes: not "the file is long" but "the file cannot be scanned".
//!
//! # Titles are read, not written twice
//!
//! Each entry's title comes from the entry itself - the heading for the early style
//! (`## D001 - Two builds from one source tree`), the first bold claim for the later one.
//! Nothing is authored here, so the index cannot disagree with the log.
//!
//! # Two details that would have made it a worse index than none
//!
//! **Anchors are computed, not assumed.** `#d001` is not where `## D001 - Two builds…`
//! anchors to; the whole heading is slugified. A short hand-written anchor would be a dead
//! link for every entry in the early style - an index that looks navigable and is not.
//!
//! **Sorted by number, not by position.** The file is not in numeric order and has not been
//! for a long time; that disorder is what let three appends in one session collide with
//! numbers already taken. A reader looking up D107 wants it where D107 belongs.

use std::path::Path;

const BEGIN: &str = "<!-- obscene:decision-index -->";
const END: &str = "<!-- /obscene:decision-index -->";

/// One entry: its number, its title, and the anchor its heading generates.
struct Entry {
    number: u32,
    title: String,
    anchor: String,
}

/// The anchor a Markdown renderer generates for a heading: lowercase, drop anything that is
/// not alphanumeric, space or hyphen, then spaces to hyphens.
fn slug(heading: &str) -> String {
    heading
        .trim()
        .to_lowercase()
        .chars()
        .filter(|c| c.is_ascii_alphanumeric() || *c == ' ' || *c == '-')
        .map(|c| if c == ' ' { '-' } else { c })
        .collect()
}

/// Every entry, ordered by number.
fn entries(text: &str) -> Vec<Entry> {
    let lines: Vec<&str> = text.split('\n').collect();
    let mut out = Vec::new();
    for (index, line) in lines.iter().enumerate() {
        let Some(rest) = line.strip_prefix("## D") else {
            continue;
        };
        let digits: String = rest.chars().take_while(char::is_ascii_digit).collect();
        let Ok(number) = digits.parse::<u32>() else {
            continue;
        };
        let trailing = rest
            .get(digits.len()..)
            .unwrap_or_default()
            .trim()
            .trim_start_matches(['-', '\u{2013}', '\u{2014}'])
            .trim();
        let mut title = trailing.to_owned();
        if title.is_empty() {
            // The later style leaves the heading bare and opens with a bold claim, which may
            // wrap over several lines.
            let blob = lines
                .iter()
                .skip(index.saturating_add(1))
                .take(7)
                .copied()
                .collect::<Vec<_>>()
                .join("\n");
            if let Some((_, after)) = blob.split_once("**")
                && let Some((claim, _)) = after.split_once("**")
            {
                title = claim.split_whitespace().collect::<Vec<_>>().join(" ");
            }
        }
        if title.is_empty() {
            "(no title)".clone_into(&mut title);
        }
        out.push(Entry {
            number,
            title,
            anchor: slug(line.get(3..).unwrap_or_default()),
        });
    }
    out.sort_by_key(|e| e.number);
    out
}

fn render(entries: &[Entry]) -> String {
    let mut rows = vec![
        BEGIN.to_owned(),
        String::new(),
        format!(
            "**{} decisions.** Generated by `obscene-tool decisions` from the entries \
             themselves - do not edit.",
            entries.len()
        ),
        String::new(),
    ];
    for entry in entries {
        rows.push(format!(
            "- [D{:03}](#{}) - {}",
            entry.number, entry.anchor, entry.title
        ));
    }
    rows.push(String::new());
    rows.push(END.to_owned());
    rows.join("\n")
}

/// Rewrite or check the index. Returns true when it is current.
pub fn run(decisions: &Path, check: bool) -> std::io::Result<bool> {
    let text = std::fs::read_to_string(decisions)?;
    let found = entries(&text);

    // Two entries may not share a number, and until today nothing said so.
    //
    // Two sessions worked in this repository at once and both appended. One reused a number
    // the other had already taken, and this tool regenerated the index over the top without
    // a word - reporting the right total, listing both, linking one. A gate that renders a
    // duplicate as though it were fine is the failure this log keeps cataloguing, occurring
    // in the tool that exists to catch drift. (D184)
    //
    // Refused in both modes rather than only under `--check`: rewriting the index over a
    // duplicated log produces a document that looks authoritative and silently loses an
    // entry's anchor.
    let duplicates: Vec<u32> = found
        .windows(2)
        .filter_map(|pair| match pair {
            [a, b] if a.number == b.number => Some(a.number),
            _ => None,
        })
        .collect();
    if let Some(first) = duplicates.first() {
        println!(
            "duplicate decision numbers in {}: {}",
            decisions.display(),
            duplicates
                .iter()
                .map(|n| format!("D{n:03}"))
                .collect::<Vec<_>>()
                .join(", ")
        );
        println!("renumber the later entry; D{first:03} is claimed twice");
        return Ok(false);
    }

    let block = render(&found);

    let updated = if text.contains(BEGIN) && text.contains(END) {
        let before = text.split(BEGIN).next().unwrap_or_default();
        let after = text.split_once(END).map(|(_, a)| a).unwrap_or_default();
        format!("{before}{block}{after}")
    } else {
        // First run: place it immediately before the first entry, under the front matter
        // that explains the statuses rather than above it.
        let Some(at) = text.find("\n## D") else {
            println!("no entries found in {}", decisions.display());
            return Ok(false);
        };
        let (head, tail) = text.split_at(at.saturating_add(1));
        format!("{head}{block}\n\n{tail}")
    };

    if check {
        if updated == text {
            println!("decision index current ({} entries)", found.len());
            return Ok(true);
        }
        println!("the decision index has drifted; run obscene-tool decisions");
        return Ok(false);
    }
    std::fs::write(decisions, updated)?;
    println!("written: {} ({} entries)", decisions.display(), found.len());
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    /// `#d001` is not where a titled heading anchors to. Getting this wrong makes every
    /// early entry a dead link while the index still looks navigable.
    #[test]
    fn anchors_are_slugified_from_the_whole_heading() {
        assert_eq!(
            slug("D001 - Two builds from one source tree"),
            "d001---two-builds-from-one-source-tree"
        );
        assert_eq!(slug("D142"), "d142");
    }

    #[test]
    fn both_heading_styles_yield_a_title() {
        let text = "## D001 - Two builds from one source tree\n\nbody\n\n## D142\n\n**The log now gates its own\nnumbering.**\n";
        let found = entries(text);
        assert_eq!(found.len(), 2);
        assert_eq!(
            found.first().map(|e| e.title.as_str()),
            Some("Two builds from one source tree")
        );
        assert_eq!(
            found.get(1).map(|e| e.title.as_str()),
            Some("The log now gates its own numbering.")
        );
    }

    /// The file is not in numeric order, and reproducing that order would make the index
    /// as hard to scan as the log.
    /// The guard nobody had watched reject anything, until it was written to.
    ///
    /// Two concurrent sessions collided on D180 and this tool rendered the result without
    /// complaint. The negative test is the point: it fails if `run` ever goes quiet again.
    #[test]
    fn a_duplicate_number_is_refused() {
        let text = "## D001\n\n**a**\n\n## D002\n\n**b**\n\n## D002\n\n**c**\n";
        let found = entries(text);
        let duplicates: Vec<u32> = found
            .windows(2)
            .filter_map(|pair| match pair {
                [a, b] if a.number == b.number => Some(a.number),
                _ => None,
            })
            .collect();
        assert_eq!(duplicates, vec![2], "a repeated number must be detected");
    }

    #[test]
    fn distinct_numbers_are_not_flagged() {
        let text = "## D001\n\n**a**\n\n## D002\n\n**b**\n\n## D003\n\n**c**\n";
        let found = entries(text);
        let duplicates: Vec<u32> = found
            .windows(2)
            .filter_map(|pair| match pair {
                [a, b] if a.number == b.number => Some(a.number),
                _ => None,
            })
            .collect();
        assert!(duplicates.is_empty(), "distinct numbers must pass");
    }

    #[test]
    fn entries_are_sorted_by_number_not_by_position() {
        let text = "## D153\n\n**c**\n\n## D142\n\n**a**\n\n## D148\n\n**b**\n";
        let numbers: Vec<u32> = entries(text).iter().map(|e| e.number).collect();
        assert_eq!(numbers, vec![142, 148, 153]);
    }
}
