//! The 8x8 bitmap font, generated from glyph art in `data/font.txt`.
//!
//! # Why the art is data
//!
//! A glyph is a picture, and a picture belongs where it can be read and corrected in place
//! rather than decoded from hex. That is why it was authored as art to begin with, and why
//! the art stayed in a data file when the generator moved to Rust: a wrong glyph is only
//! visible once it is on a screen, so making it inspectable is the whole point.
//!
//! # Uppercase only, and that is not laziness
//!
//! Ninety-five printable glyphs is a lot of art to get right. This covers uppercase, digits
//! and the punctuation the report actually contains; `obs_display_text` folds case on the way
//! in, so `035-libc/strlen` draws as `035-LIBC/STRLEN`. Still the identifier, still readable.
//!
//! A character with no glyph draws as a hollow box rather than a blank, so a gap in the table
//! is visible on screen instead of being mistaken for a space.

use std::collections::BTreeMap;
use std::fmt::Write as _;
use std::path::Path;

/// The cell is square: eight rows of eight.
const CELL: usize = 8;

/// First and last character the table covers.
const FIRST: u8 = 0x20;
const LAST: u8 = 0x5F;

const HEADER: &str = r#"/*
 * An 8x8 bitmap font, one byte per row, high bit leftmost.
 *
 * Generated by obscene-tool font from the art in data/font.txt. Edit the art, not this file.
 *
 * # Uppercase only, and why that is not laziness
 *
 * Ninety-five printable glyphs is a lot of art to get right, and a wrong one is only
 * visible once it is on a screen. This covers uppercase, digits and the punctuation the
 * report actually contains; `obs_draw_text` folds case on the way in, so
 * `035-libc/strlen` draws as `035-LIBC/STRLEN`. Still the identifier, still readable.
 *
 * A character with no glyph draws as a hollow box rather than a blank, so a gap in the
 * table is visible on screen instead of being mistaken for a space.
 */

#include "obscene/display.h"

/* Indexed from OBS_FONT_FIRST. Rows are top to bottom. */
const unsigned char obs_font[OBS_FONT_COUNT][OBS_FONT_HEIGHT] = {
"#;

/// Art for every glyph, keyed by character code, plus the fallback.
pub struct Art {
    /// The hollow box drawn for a slot with no art.
    pub fallback: Vec<String>,
    /// One entry per drawn glyph.
    pub glyphs: BTreeMap<u8, Vec<String>>,
}

/// Read the art.
pub fn read(root: &Path) -> std::io::Result<Art> {
    let text = std::fs::read_to_string(root.join("data").join("font.txt"))?;
    let mut art = Art {
        fallback: Vec::new(),
        glyphs: BTreeMap::new(),
    };
    // `None` outside a block; `Some(None)` inside the fallback; `Some(Some(code))` inside a
    // glyph.
    let mut current: Option<Option<u8>> = None;
    let mut rows: Vec<String> = Vec::new();

    for line in text.lines() {
        if let Some(rest) = line.strip_prefix('@') {
            match current.take() {
                Some(None) => art.fallback = std::mem::take(&mut rows),
                Some(Some(code)) => {
                    art.glyphs.insert(code, std::mem::take(&mut rows));
                }
                None => rows.clear(),
            }
            let mut fields = rest.split_whitespace();
            match fields.next() {
                Some("fallback") => current = Some(None),
                Some("glyph") => {
                    let code = fields
                        .next()
                        .and_then(|hex| u8::from_str_radix(hex, 16).ok());
                    current = code.map(Some);
                }
                _ => current = None,
            }
            continue;
        }
        // Inside a block, `#` is a set pixel and not a comment marker.
        //
        // Treating it as one dropped every art row whose leftmost column is lit - the glyph
        // for `#` itself lost two of its eight rows and the generator refused it. Comments
        // only exist outside blocks, which is where the file actually uses them.
        if current.is_some() && !line.trim().is_empty() {
            rows.push(line.to_owned());
        }
    }
    match current {
        Some(None) => art.fallback = rows,
        Some(Some(code)) => {
            art.glyphs.insert(code, rows);
        }
        None => {}
    }
    Ok(art)
}

/// One glyph's rows, as bytes. `#` is set, anything else is clear.
///
/// Refused rather than padded when the art is the wrong size: a glyph one row short would
/// otherwise silently borrow a row from whatever follows it, and the fault would only be
/// visible on a screen.
pub fn rows_to_bytes(rows: &[String]) -> Result<Vec<u8>, String> {
    if rows.len() != CELL {
        return Err(format!("glyph has {} rows, expected {CELL}", rows.len()));
    }
    let mut out = Vec::with_capacity(CELL);
    for row in rows {
        if row.chars().count() != CELL {
            return Err(format!(
                "row {row:?} is {} wide, expected {CELL}",
                row.chars().count()
            ));
        }
        let mut bits = 0u8;
        for (index, ch) in row.chars().enumerate() {
            if ch == '#' {
                let shift = CELL.saturating_sub(1).saturating_sub(index);
                bits |= 1u8 << shift;
            }
        }
        out.push(bits);
    }
    Ok(out)
}

/// Write the table. Returns true when all the art was usable.
pub fn run(root: &Path, check: bool) -> std::io::Result<bool> {
    let art = read(root)?;
    let mut text = String::from(HEADER);
    let mut drawn = 0usize;

    for code in FIRST..=LAST {
        let rows = art.glyphs.get(&code);
        if rows.is_some() {
            drawn = drawn.saturating_add(1);
        }
        let bytes = match rows_to_bytes(rows.unwrap_or(&art.fallback)) {
            Ok(bytes) => bytes,
            Err(why) => {
                println!("glyph {code:#04X}: {why}");
                return Ok(false);
            }
        };
        let cells: Vec<String> = bytes.iter().map(|b| format!("0x{b:02X}")).collect();
        let label = if code == b' ' {
            "space".to_owned()
        } else {
            (code as char).to_string()
        };
        let _ = writeln!(text, "    {{{}}}, /* {label} */", cells.join(", "));
    }
    text.push_str("};\n");

    let path = crate::sections::find_file(root, "font.c");
    let slots = usize::from(LAST.saturating_sub(FIRST)).saturating_add(1);
    if check {
        let current = std::fs::read_to_string(&path).unwrap_or_default();
        if current == text {
            println!("font.c current ({slots} slots, {drawn} drawn)");
            return Ok(true);
        }
        println!("font.c is out of date - regenerate it");
        return Ok(false);
    }
    std::fs::write(&path, text)?;
    println!("wrote src/font.c: {slots} slots, {drawn} drawn, rest hollow");
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    fn art(rows: &[&str]) -> Vec<String> {
        rows.iter().map(|r| (*r).to_owned()).collect()
    }

    /// High bit leftmost, which is what the drawing code shifts against.
    #[test]
    fn a_row_packs_high_bit_first() {
        let glyph = art(&[
            "#.......", ".......#", "########", "........", "........", "........", "........",
            "........",
        ]);
        let bytes = rows_to_bytes(&glyph).expect("eight by eight");
        assert_eq!(bytes.first(), Some(&0x80));
        assert_eq!(bytes.get(1), Some(&0x01));
        assert_eq!(bytes.get(2), Some(&0xFF));
        assert_eq!(bytes.get(3), Some(&0x00));
    }

    /// A glyph one row short would silently borrow a row from whatever follows, and the
    /// fault would only be visible on a screen.
    #[test]
    fn wrong_sized_art_is_refused() {
        assert!(rows_to_bytes(&art(&["########"])).is_err());
        let narrow = art(&["###", "###", "###", "###", "###", "###", "###", "###"]);
        assert!(rows_to_bytes(&narrow).is_err());
    }

    /// `#` is a set pixel, not a comment marker. Reading it as one cost the glyph for `#`
    /// two of its rows.
    #[test]
    fn a_leading_hash_is_a_pixel_inside_a_block() {
        let dir = std::env::temp_dir().join("obscene-font-hash");
        std::fs::create_dir_all(dir.join("data")).expect("temp dir");
        std::fs::write(
            dir.join("data").join("font.txt"),
            "# a real comment, outside any block
@glyph 23
#.#.#.#.
........
#.#.#.#.
             ........
#.#.#.#.
........
#.#.#.#.
........
@end
",
        )
        .expect("write");
        let art = read(&dir).expect("read");
        let glyph = art.glyphs.get(&0x23).expect("the hash glyph");
        assert_eq!(glyph.len(), 8, "every row must survive: {glyph:?}");
        std::fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn anything_that_is_not_a_hash_is_clear() {
        let glyph = art(&[
            "..#..#..", "        ", "--------", "........", "........", "........", "........",
            "........",
        ]);
        let bytes = rows_to_bytes(&glyph).expect("eight by eight");
        assert_eq!(bytes.first(), Some(&0b0010_0100));
        assert_eq!(bytes.get(1), Some(&0), "spaces are clear");
        assert_eq!(bytes.get(2), Some(&0), "so is anything else");
    }
}
