//! `include/obscene/self_header.gen.h`, generated from selfish's SELF format table.
//!
//! # Why this is generated and not written
//!
//! The on-console audit (`048-selfaudit`) compares a real SELF's header against the values the
//! format table pins, and reports which the current generation keeps. Those values are
//! **selfish's**, from `data/self-format.tsv`, derived from cited previous-generation sources.
//! A hand-copied second table in C would be exactly the "one constant, two homes, eventually
//! two values" failure both projects exist to prevent - so this reads selfish's table through
//! the same function selfish's own audit uses, `selfish_container::table::fixed_fields`, and
//! emits the rows the probe checks.
//!
//! The magic is left out: it identifies the generation rather than being a row a newer file
//! should match, so comparing it against a previous-generation value would report the split
//! itself as a difference. (matches `selfish_container::audit`, D084)

use std::fmt::Write as _;
use std::path::Path;

use selfish_abi::Generation;
use selfish_container::table;

/// A container magic as the little-endian u32 a reader gets from offset 0.
fn magic_word(generation: Generation) -> u64 {
    let bytes = generation.container_magic();
    u64::from(bytes[0])
        | (u64::from(bytes[1]) << 8)
        | (u64::from(bytes[2]) << 16)
        | (u64::from(bytes[3]) << 24)
}

/// Render the header from selfish's table.
fn render() -> String {
    let mut out = String::new();
    out.push_str(
        "/* Generated by `obscene-tool self-header` from selfish::container::table.\n\
         * Do not edit by hand. */\n\n\
         #ifndef OBSCENE_SELF_HEADER_GEN_H\n\
         #define OBSCENE_SELF_HEADER_GEN_H\n\n\
         /* Layout of a container field the self-audit check confirms. */\n\
         typedef struct {\n\
             const char *field;\n\
             unsigned int offset;\n\
             unsigned int size;\n\
             unsigned long long expected;\n\
         } obs_self_field;\n\n\
         /* Fixed fields identical across both console generations. */\n\
         static const obs_self_field obs_self_fields[] = {\n",
    );

    for row in table::fixed_fields("self_header") {
        // The magic is the generation marker, not a row to confirm.
        if row.field == "magic" {
            continue;
        }
        let _ = writeln!(
            out,
            "    {{\"{}\", {:#04x}, {}, {:#x}ull}},",
            row.field, row.offset, row.size, row.value
        );
    }

    out.push_str("};\n\n");

    // The container magics, both generations, as the LE word read from offset 0. The audit uses
    // these only to recognise that a file *is* a SELF while scanning - which generation it is
    // then falls out of the value itself. Kept out of the confirm rows above for the same reason
    // `audit` excludes it: a magic differing across generations is the split, not a mismatch.
    out.push_str(
        "/* Container magics (LE word at offset 0), both generations, for recognising a SELF. */\n\
         static const unsigned long long obs_self_magics[] = {\n",
    );
    let _ = writeln!(
        out,
        "    {:#x}ull, /* current generation */",
        magic_word(Generation::Current)
    );
    let _ = writeln!(
        out,
        "    {:#x}ull, /* previous generation */",
        magic_word(Generation::Previous)
    );
    out.push_str("};\n\n#endif /* OBSCENE_SELF_HEADER_GEN_H */\n");
    out
}

/// Regenerate or check `include/obscene/self_header.gen.h`.
///
/// # Errors
///
/// If the header cannot be written.
pub fn run(root: &Path, check: bool) -> Result<bool, Box<dyn std::error::Error>> {
    let fresh = render();
    let path = root
        .join("include")
        .join("obscene")
        .join("self_header.gen.h");

    let count = table::fixed_fields("self_header")
        .iter()
        .filter(|row| row.field != "magic")
        .count();

    if check {
        let current = std::fs::read_to_string(&path).unwrap_or_default();
        if current == fresh {
            println!("self_header.gen.h current ({count} rows)");
            return Ok(true);
        }
        println!("self_header.gen.h is out of date - regenerate it");
        return Ok(false);
    }

    std::fs::write(&path, fresh)?;
    println!(
        "wrote {} ({count} rows from selfish's table)",
        path.display()
    );
    Ok(true)
}
