//! Compile the compute shaders in `src/shaders/*.comp` and embed them as SPIR-V.
//!
//! # Why the output is committed
//!
//! `include/obscene/gpu_shaders.gen.h` holds the SPIR-V for every kernel as C arrays, so the
//! host and Deck builds need no shader compiler - only *regenerating* does. That is the same
//! arrangement the censuses use: a generated file under version control, plus a command to
//! rebuild it, run where the tool exists.
//!
//! # Why word arrays and not bytes
//!
//! Vulkan's `pCode` is `const uint32_t*` and must be four-byte aligned. A `uint32_t[]` is
//! aligned by the type; a `char[]` cast to `uint32_t*` is not guaranteed to be. The SPIR-V
//! file is little-endian words, decoded here so the array is correct on any host that
//! compiles it.

use std::path::Path;

/// How many inputs a kernel takes, from an `obs-arity: N` directive in the shader.
///
/// Absent means one - the unary kernels, which need no directive. The section reads this to
/// lay out its buffer and pick the record kind.
fn arity(source: &str) -> u32 {
    source
        .split("obs-arity:")
        .nth(1)
        .map(|rest| {
            rest.trim_start()
                .chars()
                .take_while(char::is_ascii_digit)
                .collect::<String>()
        })
        .and_then(|digits| digits.parse().ok())
        .unwrap_or(1)
}

/// Little-endian words, which is what SPIR-V is and what Vulkan wants.
fn words(data: &[u8]) -> Option<Vec<u32>> {
    if data.is_empty() || !data.len().is_multiple_of(4) {
        return None;
    }
    // `as_chunks` rather than `chunks_exact(4)`: it yields `[u8; 4]` directly, so there is no
    // copy into a temporary and no slice-length assumption for the compiler to lose track of.
    // The remainder is empty by the multiple-of-four check above.
    let (quads, _rest) = data.as_chunks::<4>();
    Some(quads.iter().copied().map(u32::from_le_bytes).collect())
}

/// Render the header from already-compiled SPIR-V.
///
/// Separated from the compiling so it can be tested without `glslangValidator`, which is
/// exactly the dependency that keeps this generator out of a normal build.
#[must_use]
pub fn render(kernels: &[(String, u32, Vec<u32>)]) -> String {
    let mut out = vec![
        "/* Generated by obscene-tool shaders. Do not edit by hand.".to_owned(),
        " *".to_owned(),
        " * SPIR-V for every kernel under src/shaders, embedded so the build needs no shader"
            .to_owned(),
        " * compiler. Regenerate in the build VM (which has glslangValidator) after changing"
            .to_owned(),
        " * a shader. */".to_owned(),
        "#ifndef OBSCENE_GPU_SHADERS_GEN_H".to_owned(),
        "#define OBSCENE_GPU_SHADERS_GEN_H".to_owned(),
        "#include <stdint.h>".to_owned(),
        String::new(),
    ];

    for (name, _, code) in kernels {
        out.push(format!("static const uint32_t obs_shader_{name}[] = {{"));
        for chunk in code.chunks(6) {
            let row: Vec<String> = chunk.iter().map(|w| format!("0x{w:08x}")).collect();
            out.push(format!("    {},", row.join(", ")));
        }
        out.push("};".to_owned());
        out.push(String::new());
    }

    // The kernel list, as an X-macro. The section expands it once to build its sweep table,
    // so adding a shader is dropping a `.comp` file and regenerating - no C edit. Same idiom
    // the census uses, for the same reason: the list has exactly one home.
    out.push(
        "/* Every kernel. Expand with an X that takes (name, arity); each name has a".to_owned(),
    );
    out.push(" * matching obs_shader_<name>[] above, and arity is its input count. */".to_owned());
    out.push("#define OBS_GPU_KERNELS(X) \\".to_owned());
    let last = kernels.len().saturating_sub(1);
    for (index, (name, count, _)) in kernels.iter().enumerate() {
        let tail = if index == last { "" } else { " \\" };
        out.push(format!("    X({name}, {count}){tail}"));
    }
    out.push(String::new());
    out.push("#endif /* OBSCENE_GPU_SHADERS_GEN_H */".to_owned());
    out.join("\n") + "\n"
}

/// Compile every shader and write or check the header. Returns true when it is current.
pub fn run(root: &Path, check: bool) -> Result<bool, Box<dyn std::error::Error>> {
    let dir = root.join("src").join("shaders");
    let mut sources: Vec<_> = std::fs::read_dir(&dir)?
        .filter_map(Result::ok)
        .map(|e| e.path())
        .filter(|p| {
            p.extension()
                .is_some_and(|e| e.eq_ignore_ascii_case("comp"))
        })
        .collect();
    sources.sort();
    if sources.is_empty() {
        return Err(format!("no shaders in {}", dir.display()).into());
    }

    let mut kernels = Vec::new();
    for source in &sources {
        let name = source
            .file_stem()
            .and_then(|s| s.to_str())
            .unwrap_or_default()
            .to_owned();
        let text = std::fs::read_to_string(source)?;
        let spv = source.with_extension("comp.spv");
        let outcome = std::process::Command::new("glslangValidator")
            .arg("-V")
            .arg(source)
            .arg("-o")
            .arg(&spv)
            .output()?;
        if !outcome.status.success() {
            let _ = std::fs::remove_file(&spv);
            return Err(format!(
                "{name}: glslangValidator failed:\n{}\n{}",
                String::from_utf8_lossy(&outcome.stdout),
                String::from_utf8_lossy(&outcome.stderr)
            )
            .into());
        }
        let data = std::fs::read(&spv)?;
        let _ = std::fs::remove_file(&spv);
        let Some(code) = words(&data) else {
            return Err(format!(
                "{name}: SPIR-V is {} bytes, not a positive multiple of 4",
                data.len()
            )
            .into());
        };
        kernels.push((name, arity(&text), code));
    }

    let fresh = render(&kernels);
    let path = root
        .join("include")
        .join("obscene")
        .join("gpu_shaders.gen.h");

    // `--check` is the drift gate. A committed generated file is only trustworthy if
    // something fails when it falls out of step with its source; a shader edited without
    // regenerating would otherwise ship stale SPIR-V.
    if check {
        let current = std::fs::read_to_string(&path).unwrap_or_default();
        if current == fresh {
            println!("gpu_shaders.gen.h current ({} kernels)", kernels.len());
            return Ok(true);
        }
        println!("gpu_shaders.gen.h is out of date - regenerate it");
        return Ok(false);
    }
    std::fs::write(&path, fresh)?;
    let names: Vec<&str> = kernels.iter().map(|(n, _, _)| n.as_str()).collect();
    println!(
        "embedded {} shader(s): {} -> {}",
        names.len(),
        names.join(", "),
        path.display()
    );
    Ok(true)
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn arity_defaults_to_one_when_undirected() {
        assert_eq!(arity("#version 450\nvoid main() {}\n"), 1);
        assert_eq!(arity("// obs-arity: 3\n#version 450\n"), 3);
        assert_eq!(arity("/* obs-arity:2 */\n"), 2);
    }

    /// SPIR-V is little-endian words. Decoding here is what makes the array correct on any
    /// host that compiles the generated header.
    #[test]
    fn spirv_decodes_as_little_endian_words() {
        assert_eq!(words(&[0x03, 0x02, 0x23, 0x07]), Some(vec![0x0723_0203]));
        assert_eq!(words(&[]), None, "empty is not valid SPIR-V");
        assert_eq!(words(&[1, 2, 3]), None, "a partial word is not valid");
    }

    #[test]
    fn the_last_kernel_row_carries_no_continuation() {
        let rendered = render(&[
            ("one".to_owned(), 1, vec![1, 2]),
            ("two".to_owned(), 3, vec![3]),
        ]);
        assert!(rendered.contains("    X(one, 1) \\\n"));
        assert!(rendered.contains("    X(two, 3)\n"));
        assert!(rendered.contains("static const uint32_t obs_shader_one[] = {"));
        assert!(rendered.contains("0x00000001, 0x00000002,"));
    }
}
