//! Generate obSCEne's payload resolution table: read the payload's imports, find each in the
//! target libraries, emit `payload_table.c` for the crt0 (`SELFish/runtime/crt0.c`) to link against.
//!
//!   `gen_payload_table <payload.elf> <libkernel.sprx> [<console_path> <local.sprx>]...`
//!
//! This is obSCEne's build orchestration - a *consumer* of selfish's format primitives
//! (`dynamic_symbols`, `dynamic::symbols`, `Nid`), not a format library itself. The per-firmware
//! vaddrs it emits are measurements of one console's libraries and stay here, with the probe,
//! exactly as selfish's charter requires. selfish reads the formats; obSCEne decides what to
//! build from them.
use selfish_nid::Nid;
use std::collections::BTreeMap;
use std::env;

/// Every `<encoded-nid-prefix> -> vaddr` a vendor library exports.
fn exports(path: &str) -> BTreeMap<String, u64> {
    let bytes = std::fs::read(path).expect("read library");
    let elf = selfish_elf::Elf::parse(&bytes).expect("parse library");
    let (segment, info) = elf.tables().expect("tables").expect("vendor tables");
    let strings = selfish_elf::dynamic::strings(segment, &info);
    let symbols = selfish_elf::dynamic::symbols(segment, &info).expect("symbols");
    let mut out = BTreeMap::new();
    for s in &symbols {
        if s.is_import() || s.name_offset == 0 || s.value == 0 {
            continue;
        }
        if let Ok(name) = selfish_elf::dynamic::string_at(strings, s.name_offset) {
            let prefix = name.split('#').next().unwrap_or(name).to_owned();
            out.entry(prefix).or_insert(s.value);
        }
    }
    out
}

/// The plain payload's undefined dynamic symbols - its imports. Reads `.dynsym` through
/// selfish's `dynamic_symbols`, the primitive added for exactly this (no hand-rolled parse).
fn imports(path: &str) -> Vec<String> {
    let bytes = std::fs::read(path).expect("read payload");
    let elf = selfish_elf::Elf::parse(&bytes).expect("parse payload");
    let sections = elf.sections().expect("sections").expect("has sections");
    let (symbols, strings) = sections.dynamic_symbols().expect("no .dynsym");
    let mut out = Vec::new();
    for s in &symbols {
        if s.is_undefined()
            && s.name_offset != 0
            && let Some(name) = selfish_elf::section::string_at(strings, s.name_offset)
            && !name.is_empty()
        {
            out.push(name.to_owned());
        }
    }
    out.sort();
    out.dedup();
    out
}

fn main() {
    let args: Vec<String> = env::args().collect();
    if args.len() < 3 {
        eprintln!("usage: gen_payload_table <payload.elf> <libkernel.sprx> [path local.sprx]...");
        std::process::exit(2);
    }
    // Indexed through `get` rather than `[]`: the length was checked above, but a bounds check
    // that lives two lines away from the index is one somebody moves.
    let payload = args.get(1).expect("argument count checked above");
    let mut lib_paths: Vec<String> = vec![String::from("(libkernel)")];
    let mut lib_tables: Vec<BTreeMap<String, u64>> =
        vec![exports(args.get(2).expect("argument count checked above"))];
    let mut i: usize = 3;
    while i.saturating_add(1) < args.len() {
        let (Some(path), Some(library)) = (args.get(i), args.get(i.saturating_add(1))) else {
            break;
        };
        lib_paths.push(path.clone());
        lib_tables.push(exports(library));
        i = i.saturating_add(2);
    }

    let want = imports(payload);
    let mut rows: Vec<(String, usize, u64)> = Vec::new();
    let mut unresolved: Vec<String> = Vec::new();
    for name in &want {
        let prefix = Nid::of(name).encode();
        let mut found = None;
        for (lib, table) in lib_tables.iter().enumerate() {
            if let Some(&vaddr) = table.get(&prefix) {
                found = Some((lib, vaddr));
                break;
            }
        }
        match found {
            Some((lib, vaddr)) => rows.push((name.clone(), lib, vaddr)),
            None => unresolved.push(name.clone()),
        }
    }

    let bootstrap = |nm: &str| -> u64 {
        *lib_tables
            .first()
            .expect("libkernel is pushed before this runs")
            .get(&Nid::of(nm).encode())
            .unwrap_or_else(|| {
                eprintln!("libkernel is missing {nm}");
                std::process::exit(1);
            })
    };

    println!("/* generated by obscene-tool gen_payload_table - do not edit */");
    println!("struct obs_import {{ const char *name; unsigned lib; unsigned long vaddr; }};");
    println!(
        "const unsigned long obs_getpid_vaddr = 0x{:x}UL;",
        bootstrap("getpid")
    );
    println!(
        "const unsigned long obs_loadstart_vaddr = 0x{:x}UL;",
        bootstrap("sceKernelLoadStartModule")
    );
    println!(
        "const unsigned long obs_modinfo_vaddr = 0x{:x}UL;",
        bootstrap("sceKernelGetModuleInfo")
    );
    println!("const struct obs_import obs_imports[] = {{");
    for (name, lib, vaddr) in &rows {
        println!("  {{ \"{name}\", {lib}, 0x{vaddr:x}UL }},");
    }
    println!("}};");
    println!("const unsigned obs_import_count = {};", rows.len());
    println!("const char *const obs_lib_paths[] = {{");
    for p in &lib_paths {
        println!("  \"{p}\",");
    }
    println!("}};");
    println!("const unsigned obs_lib_count = {};", lib_paths.len());
    if !unresolved.is_empty() {
        eprintln!("unresolved ({}):", unresolved.len());
        for u in &unresolved {
            eprintln!("  {u}");
        }
    }
    eprintln!("resolved {} of {} imports", rows.len(), want.len());
}
