/* ---- 048-selfaudit ---------------------------------------------------------
 *
 * Confirm selfish's SELF format table against a real current-generation container, on
 * the console, reporting only the verdict.
 *
 * # It finds the container, it is not told where one is
 *
 * An earlier version named specific title ids - `/system/vsh/app/NPXS40112/eboot.bin`
 * and a couple of siblings. That was wrong twice over: it only ever checked containers
 * somebody had written down, and a firmware that shuffled its title ids would find
 * nothing. This walks the application directories with `sceKernelGetdents` and audits
 * the first real container it finds. The only paths named here are the **structural
 * roots** where applications live, the way `/bin` is where programs live - not any
 * particular title. (selfish#D087)
 *
 * # What replaced the dump, and why
 *
 * This began as a probe that copied a real SELF header off the box to a file, for
 * `selfish audit` to read on a dev machine. That carried the vendor header's bytes off
 * the console - the extract-and-read-offline side of the provenance line. This reads
 * the header transiently *here*, compares it against the values selfish's format table
 * pins, and reports which the current generation keeps. The header bytes never land in
 * a file and never leave the box; only the finding does. (selfish#D086)
 *
 * # Where the expected values come from
 *
 * `include/obscene/self_header.gen.h`, generated by `obscene-tool selfheader` from
 * selfish's `data/self-format.tsv` and `selfish-abi`. Not a second copy of the table -
 * a projection of the one table into C, regenerated from it, drift-gated by
 * `verify.sh`. The magics recognise that a file *is* a SELF while scanning; the fixed
 * rows are what a match confirms; the magic is excluded from the confirm rows because
 * it identifies the generation rather than being a row a newer file should match.
 *
 * # Vendor container versus our own
 *
 * A container found under a system or user application root is the vendor's, which is
 * the point.
 * `/app0` is the *running app's own* eboot - a real vendor container when obSCEne runs
 * as a payload inside a hijacked app, but obSCEne's own fake SELF when it runs as a
 * standalone package. So the roots are scanned first and `/app0` is the last resort,
 * and the verdict says which it read, so a self-check is never mistaken for a vendor
 * confirmation.
 *
 * # What it reports on a difference
 *
 * A matching row reveals nothing not already public. A row that differs is a finding,
 * and the measured value is reported with it, because "flags differs" without the value
 * is not actionable - a format constant the probe observed, reported the way it reports
 * every syscall return, not a meaning read off the bytes. What a difference *means* at
 * the new generation still needs a citable source (selfish principle 1); the probe
 * states the difference and stops.
 */

#include "obscene/harness.h"
#include "obscene/platform.h"
#include "obscene/report.h"
#include "obscene/runtime.h"
#include "obscene/sections.h"
#include "obscene/self_header.gen.h"
#include "obscene/status.h"

/* Enough of the header to cover every fixed row. self_header is 0x20 bytes; a little
 * more costs nothing and future rows past 0x20 would be covered too. */
#define OBS_SELFAUDIT_LEN 0x40

/* The structural roots where applications live. Not title ids - the directories a title
 * id sits *inside*. The walk discovers whatever is there. A system app is the vendor
 * container the audit wants; `/app0` is the running app itself and is tried last (see
 * the header comment). */
static const char *const obs_app_roots[] = {
    "/system/vsh/app",
    "/user/app",
};
#define OBS_APP0_EBOOT "/app0/eboot.bin"

/* Read a little-endian value of `size` bytes at `offset`. */
static unsigned long long obs_le(const unsigned char *buf, unsigned int offset,
                                 unsigned int size) {
    unsigned long long value = 0;
    for (unsigned int i = 0; i < size; i++) {
        value |= (unsigned long long)buf[offset + i] << (i * 8u);
    }
    return value;
}

/* Read up to `cap` bytes of a path into `buf`. Returns the count, or -1. The bytes live
 * only for this check and are never written anywhere.
 *
 * # `cap` is a parameter because it used to be a constant
 *
 * This read `OBS_SELFAUDIT_LEN` bytes whatever it was handed, and two of its callers
 * hand it a 32-byte buffer. `check_metadata_differential` smashed 32 bytes of its own
 * stack on every file it read - once per title directory, thousands of times - over the
 * counters and the dirent loop state living beside them. That is what produced 45,792
 * "installed titles", and a claim of 2,672 containers under the very roots
 * `confirm-table` had just found nothing readable in: one of those two numbers came
 * through a correctly-sized buffer and the other did not. The read is now bounded by
 * what the caller owns, so a short buffer cannot be overrun again. (D284)
 *
 * Through `sceKernelOpen`/`Read`, the same family the directory walk uses - one
 * consistent set of raw syscalls, so a file and a directory resolve the same way. (The
 * report sink's own backend is for writing obSCEne's report, not for reading vendor
 * files.) */
static long obs_read_header(const char *path, unsigned char *buf, size_t cap) {
    if (cap == 0) {
        return -1;
    }
    int fd = sceKernelOpen(path, OBS_O_RDONLY, 0);
    if (fd < 0) {
        return -1;
    }
    long total = 0;
    while (total < (long)cap) {
        sce_ssize_t n = sceKernelRead(fd, buf + total, (size_t)((long)cap - total));
        if (n < 0) {
            sceKernelClose(fd);
            return -1;
        }
        if (n == 0) {
            break;
        }
        total += (long)n;
    }
    sceKernelClose(fd);
    return total;
}

/* Is the header a SELF? True when its first word is one of the container magics. */
static int obs_is_self(const unsigned char *buf) {
    unsigned long long magic = obs_le(buf, 0, 4);
    for (unsigned int i = 0; i < OBS_COUNT(obs_self_magics); i++) {
        if (magic == obs_self_magics[i]) {
            return 1;
        }
    }
    return 0;
}

/* Append `b` onto `dst` at `k`, bounded. Returns the new length. A tiny freestanding
 * join, so the probe builds `<root>/<name>/eboot.bin` without a libc string call. */
static size_t obs_append(char *dst, size_t k, size_t cap, const char *b) {
    while (*b && k < cap - 1) {
        dst[k++] = *b++;
    }
    dst[k] = '\0';
    return k;
}
static size_t obs_append_n(char *dst, size_t k, size_t cap, const char *b, size_t n) {
    for (size_t i = 0; i < n && k < cap - 1; i++) {
        dst[k++] = b[i];
    }
    dst[k] = '\0';
    return k;
}

/* Walk one application root. For each subdirectory it holds, try
 * `<root>/<name>/eboot.bin`; the first that reads as a SELF is written into `found` and
 * 1 is returned. */
static int obs_scan_root(const char *root, char *found, size_t found_cap,
                         unsigned char *buf, size_t buf_cap) {
    int dir = sceKernelOpen(root, OBS_O_RDONLY, 0);
    if (dir < 0) {
        return 0; /* not reachable, or not present - the reach section explains which */
    }

    char dents[4096];
    int hit = 0;
    for (;;) {
        sce_ssize_t n = sceKernelGetdents(dir, dents, (int)sizeof dents);
        if (n <= 0) {
            break;
        }
        long pos = 0;
        while (pos + OBS_DIRENT_NAME < n) {
            unsigned int reclen = (unsigned int)obs_le(
                (const unsigned char *)dents + pos, OBS_DIRENT_RECLEN, 2);
            if (reclen == 0) {
                break; /* a zero record length would not advance - stop rather than spin
                        */
            }
            unsigned char type = (unsigned char)dents[pos + OBS_DIRENT_TYPE];
            unsigned int namlen = (unsigned char)dents[pos + OBS_DIRENT_NAMLEN];
            const char *name = dents + pos + OBS_DIRENT_NAME;
            /* Only directories, and not the two that point at the tree itself. */
            int dot = (namlen == 1 && name[0] == '.') ||
                      (namlen == 2 && name[0] == '.' && name[1] == '.');
            if (type == OBS_DT_DIR && !dot && namlen > 0) {
                size_t k = obs_append(found, 0, found_cap, root);
                k = obs_append(found, k, found_cap, "/");
                k = obs_append_n(found, k, found_cap, name, namlen);
                obs_append(found, k, found_cap, "/eboot.bin");
                if (obs_read_header(found, buf, buf_cap) >= (long)buf_cap &&
                    obs_is_self(buf)) {
                    hit = 1;
                    break;
                }
            }
            pos += (long)reclen;
        }
        if (hit) {
            break;
        }
    }
    sceKernelClose(dir);
    return hit;
}

static obs_result check_confirm_format_table(void) {
    OBS_REQUIRE(&sceKernelOpen);
    OBS_REQUIRE(&sceKernelClose);
    OBS_REQUIRE(&sceKernelRead);
    OBS_REQUIRE(&sceKernelGetdents);

    static unsigned char buf[OBS_SELFAUDIT_LEN];
    char found[1024];
    const char *origin = 0; /* "vendor" or "own app", for the verdict */

    /* Vendor application roots first: those hold containers that are not ours. */
    for (unsigned int i = 0; i < OBS_COUNT(obs_app_roots); i++) {
        if (obs_scan_root(obs_app_roots[i], found, sizeof found, buf, sizeof buf)) {
            origin = "vendor";
            break;
        }
    }

    /* Only if none was found, the running app's own eboot - which may be obSCEne's own
     * SELF. */
    if (!origin) {
        size_t k = obs_append(found, 0, sizeof found, OBS_APP0_EBOOT);
        (void)k;
        if (obs_read_header(found, buf, sizeof buf) >= (long)sizeof buf &&
            obs_is_self(buf)) {
            origin = "own app";
        }
    }

    if (!origin) {
        /* Nothing readable was a SELF. On host and for a sandboxed module this is
         * expected; the reach section says which. A measurement, so it skips rather
         * than fails. */
        return obs_skip("no SELF container was reachable from this process");
    }

    obs_report_sysinfo("selfaudit/source", origin, found);

    /* The measured value is reported on **every** row, match or not.
     *
     * It used to be printed only on a difference, on the reasoning that a match repeats
     * the table the reader already has. The effect was backwards: the number was
     * withheld in the one case where it is already public - these nine values are in
     * `selfish/data/self-format.tsv`, cited to OpenOrbis, shadPS4 and fpPS4 - and
     * printed in the case where it is genuinely new. Nothing is protected by omitting a
     * constant this repository already commits, and a report that says `matches`
     * without saying what matched cannot be diffed against the next firmware, or read
     * by anyone who does not have the table open beside it. So: always the value.
     * (D285)
     *
     * A difference carries the table's value too, because the point of the line is the
     * gap. */
    unsigned int rows =
        (unsigned int)(sizeof(obs_self_fields) / sizeof(obs_self_fields[0]));
    unsigned int matched = 0;
    for (unsigned int i = 0; i < rows; i++) {
        const obs_self_field *row = &obs_self_fields[i];
        unsigned long long value = obs_le(buf, row->offset, row->size);
        char text[64];
        size_t n = obs_format_hex(text, value);
        text[n] = '\0';
        if (value == row->expected) {
            matched++;
            obs_report_sysinfo(row->field, "matches", text);
        } else {
            /* `<measured> (table: <expected>)` - both halves, so the line is actionable
             * alone. obs_format_hex writes its own `0x`, so the parts are appended as
             * they come. */
            char want[OBS_NUM_MAX];
            size_t w = obs_format_hex(want, row->expected);
            want[w] = '\0';
            n = obs_append(text, n, sizeof text, " (table: ");
            n = obs_append(text, n, sizeof text, want);
            obs_append(text, n, sizeof text, ")");
            obs_report_sysinfo(row->field, "differs", text);
        }
    }

    if (matched == rows) {
        obs_report_sysinfo(
            "selfaudit/verdict", "confirmed",
            "every fixed header row matches selfish's table at this generation");
        return obs_pass_value(matched);
    }
    obs_report_sysinfo(
        "selfaudit/verdict", "diverged",
        "some fixed rows differ - the table's current-generation rows need review");
    return obs_partial_value("the real header diverges from the table", matched);
}

static obs_result check_metadata_differential(void) {
    OBS_REQUIRE(&sceKernelOpen);
    OBS_REQUIRE(&sceKernelClose);
    OBS_REQUIRE(&sceKernelRead);
    OBS_REQUIRE(&sceKernelGetdents);

    unsigned int ps5_titles = 0;
    unsigned int ps4_titles = 0;
    unsigned int gen5_containers = 0;
    unsigned int gen4_containers = 0;

    /* 1. Inspect running application container in /app0 */
    unsigned char app0_hdr[32];
    if (obs_read_header("/app0/sce_sys/param.json", app0_hdr, sizeof app0_hdr) > 0 &&
        app0_hdr[0] == '{') {
        ps5_titles++;
    } else if (obs_read_header("/app0/sce_sys/param.sfo", app0_hdr, sizeof app0_hdr) >=
                   4 &&
               app0_hdr[0] == 0x00 && app0_hdr[1] == 'P' && app0_hdr[2] == 'S' &&
               app0_hdr[3] == 'F') {
        ps4_titles++;
    }
    if (obs_read_header("/app0/eboot.bin", app0_hdr, sizeof app0_hdr) >= 4) {
        unsigned long long magic = obs_le(app0_hdr, 0, 4);
        if (magic == obs_self_magics[0]) {
            gen5_containers++;
        } else if (magic == obs_self_magics[1]) {
            gen4_containers++;
        }
    }

    /* 2. Walk application directory roots if accessible */
    for (unsigned int r = 0; r < OBS_COUNT(obs_app_roots); r++) {
        const char *root = obs_app_roots[r];
        int dir = sceKernelOpen(root, OBS_O_RDONLY, 0);
        if (dir < 0) {
            continue;
        }
        char dents[4096];
        for (;;) {
            sce_ssize_t n = sceKernelGetdents(dir, dents, (int)sizeof dents);
            if (n <= 0) {
                break;
            }
            long pos = 0;
            while (pos + OBS_DIRENT_NAME < n) {
                unsigned int reclen = (unsigned int)obs_le(
                    (const unsigned char *)dents + pos, OBS_DIRENT_RECLEN, 2);
                if (reclen == 0) {
                    break;
                }
                unsigned char type = (unsigned char)dents[pos + OBS_DIRENT_TYPE];
                unsigned int namlen = (unsigned char)dents[pos + OBS_DIRENT_NAMLEN];
                const char *name = dents + pos + OBS_DIRENT_NAME;
                int dot = (namlen == 1 && name[0] == '.') ||
                          (namlen == 2 && name[0] == '.' && name[1] == '.');
                if (type == OBS_DT_DIR && !dot && namlen > 0) {
                    char path[1024];
                    unsigned char header[32];

                    /* Check sce_sys/param.json */
                    size_t k = obs_append(path, 0, sizeof path, root);
                    k = obs_append(path, k, sizeof path, "/");
                    k = obs_append_n(path, k, sizeof path, name, namlen);
                    obs_append(path, k, sizeof path, "/sce_sys/param.json");
                    if (obs_read_header(path, header, sizeof header) > 0 &&
                        header[0] == '{') {
                        ps5_titles++;
                    }

                    /* Check sce_sys/param.sfo */
                    k = obs_append(path, 0, sizeof path, root);
                    k = obs_append(path, k, sizeof path, "/");
                    k = obs_append_n(path, k, sizeof path, name, namlen);
                    obs_append(path, k, sizeof path, "/sce_sys/param.sfo");
                    if (obs_read_header(path, header, sizeof header) >= 4 &&
                        header[0] == 0x00 && header[1] == 'P' && header[2] == 'S' &&
                        header[3] == 'F') {
                        ps4_titles++;
                    }

                    /* Check eboot.bin container magic */
                    k = obs_append(path, 0, sizeof path, root);
                    k = obs_append(path, k, sizeof path, "/");
                    k = obs_append_n(path, k, sizeof path, name, namlen);
                    obs_append(path, k, sizeof path, "/eboot.bin");
                    if (obs_read_header(path, header, sizeof header) >= 4) {
                        unsigned long long magic = obs_le(header, 0, 4);
                        if (magic == obs_self_magics[0]) {
                            gen5_containers++;
                        } else if (magic == obs_self_magics[1]) {
                            gen4_containers++;
                        }
                    }
                }
                pos += (long)reclen;
            }
        }
        sceKernelClose(dir);
    }

    char count_buf[OBS_NUM_MAX];
    size_t l = obs_format_u64(count_buf, ps5_titles);
    count_buf[l] = '\0';
    obs_report_sysinfo("metadata/ps5_param_json", count_buf,
                       "installed titles declaring param.json");

    l = obs_format_u64(count_buf, ps4_titles);
    count_buf[l] = '\0';
    obs_report_sysinfo("metadata/ps4_param_sfo", count_buf,
                       "installed titles declaring param.sfo");

    l = obs_format_u64(count_buf, gen5_containers);
    count_buf[l] = '\0';
    obs_report_sysinfo("metadata/gen5_containers", count_buf,
                       "eboot containers with gen-5 magic (54 14 F5 EE)");

    l = obs_format_u64(count_buf, gen4_containers);
    count_buf[l] = '\0';
    obs_report_sysinfo("metadata/gen4_containers", count_buf,
                       "eboot containers with gen-4 magic (4F 15 3D 1D)");

    if (ps5_titles > 0 && ps4_titles == 0) {
        obs_report_sysinfo("metadata/verdict", "ps5_native_only",
                           "all inspected titles are native PS5");
        return obs_pass_value(ps5_titles);
    }
    if (ps5_titles > 0 && ps4_titles > 0) {
        obs_report_sysinfo("metadata/verdict", "mixed",
                           "both native PS5 and PS4 compat titles found");
        return obs_pass_value(ps5_titles + ps4_titles);
    }
    if (ps4_titles > 0) {
        obs_report_sysinfo("metadata/verdict", "ps4_compat_only",
                           "only PS4 compat titles discovered");
        return obs_pass_value(ps4_titles);
    }

    obs_report_sysinfo("metadata/verdict", "none",
                       "no installed title metadata was reachable");
    return obs_partial("no installed title metadata reachable");
}

/* ---- 048-selfaudit/container-structure
 * --------------------------------------------------------
 *
 * The container's whole measured shape, so selfish has the numbers a gen-5 package is
 * built from.
 *
 * `confirm-table` answers "do the nine fixed header constants still hold". This answers
 * "what does the rest of a real container actually contain" - the header's per-file
 * fields, the segment table, and the ex_info/npdrm blocks - as **raw measured values**.
 * It does not decode them: what a segment flag bit or an ex_info ptype value *means*
 * lives in selfish's self-format.tsv, and re-encoding that here would be a second copy
 * of a judgement that must have one home. So the report carries the number; the reader
 * turns it back into meaning against that table.
 *
 * Two provenance points, both load-bearing:
 *
 *  - The structural offsets used here (header_size at 0x0C, the segment table at 0x20
 * with a 0x20 stride, ex_info at header_size-0x70, npdrm at header_size-0x30) are
 * format facts from selfish's table, cited but not yet *projected* the way the nine
 * fixed rows are through self_header.gen.h. Promoting them into the generated header -
 * so they cannot drift from the table - is a follow-up, blocked only on the
 * generator/selfish rescaffold settling. (D286)
 *
 *  - ex_info and npdrm sit at the tail of the header on the previous generation.
 * Whether that layout holds at the current generation is exactly what is unconfirmed,
 * so the ex_info read is self-checked: if ptype is not one of the small values the
 * format admits, the block is reported as "not located" rather than as four numbers
 * that might be the wrong bytes. Principle 2 - a wrong value that reads as a finding
 * costs more than a withheld one.
 *
 * The content id inside npdrm is a title's own identifier; its presence and length are
 * format and are reported, its value is the vendor title's and is not.
 */

/* A larger window than confirm-table's 0x40: enough for the header (self_header +
 * segment table + ELF phdrs + ex_info + npdrm), which for an ordinary title is well
 * under 4 KiB. Reads are bounded by whatever was actually returned, so a short read
 * simply reports fewer fields. */
#define OBS_SELF_STRUCT_LEN 4096u

/* The ptype values the format admits (selfish self-format.tsv ptype rows), used only to
 * sanity -check that the ex_info offset landed on a real block - not to decode, which
 * is the reader's job against the same table. */
static int obs_ptype_is_known(unsigned long long ptype) {
    switch (ptype) {
    case 0x1:
    case 0x4:
    case 0x5:
    case 0x8:
    case 0x9:
    case 0xC:
    case 0xE:
    case 0xF:
        return 1;
    default:
        return 0;
    }
}

/* Report one measured u64 field as a hex value under `field`. `note` says where it was
 * read. */
static void obs_report_u64(const char *field, unsigned long long value,
                           const char *note) {
    char text[24];
    size_t n = obs_format_hex(text, value);
    text[n] = '\0';
    obs_report_sysinfo(field, text, note);
}

static obs_result check_container_structure(void) {
    OBS_REQUIRE(&sceKernelOpen);
    OBS_REQUIRE(&sceKernelClose);
    OBS_REQUIRE(&sceKernelRead);
    OBS_REQUIRE(&sceKernelGetdents);

    static unsigned char buf[OBS_SELF_STRUCT_LEN];
    char found[1024];
    const char *origin = 0;
    long got = 0;

    /* Same locate as confirm-table: vendor roots first, own /app0 last. obs_scan_root
     * fills buf and requires a full read, so a container shorter than the window is
     * rejected there; retry /app0 with a plain read so a short-but-real container is
     * still measured. */
    for (unsigned int i = 0; i < OBS_COUNT(obs_app_roots) && !origin; i++) {
        if (obs_scan_root(obs_app_roots[i], found, sizeof found, buf, sizeof buf)) {
            origin = "vendor";
            got = (long)sizeof buf;
        }
    }
    if (!origin) {
        (void)obs_append(found, 0, sizeof found, OBS_APP0_EBOOT);
        got = obs_read_header(found, buf, sizeof buf);
        if (got >= 4 && obs_is_self(buf)) {
            origin = "own app";
        }
    }
    if (!origin) {
        return obs_skip("no SELF container was reachable from this process");
    }

    obs_report_sysinfo("structure/source", origin, found);

    /* self_header per-file fields. All within the first 0x20 bytes, so any real
     * container covers them. Raw measurements: header_size and meta_size bound the
     * metadata region, file_size and segment_count size the body. */
    unsigned long long header_size = obs_le(buf, 0x0C, 2);
    unsigned long long meta_size = obs_le(buf, 0x0E, 2);
    unsigned long long file_size = obs_le(buf, 0x10, 8);
    unsigned long long segment_count = obs_le(buf, 0x18, 2);
    obs_report_u64("structure/header_size", header_size, "self_header 0x0C");
    obs_report_u64("structure/meta_size", meta_size, "self_header 0x0E");
    obs_report_u64("structure/file_size", file_size, "self_header 0x10");
    obs_report_u64("structure/segment_count", segment_count, "self_header 0x18");

    /* The segment table at 0x20, one 0x20-byte entry per count. Each entry's flags (the
     * encrypted /signed/blocked/compressed/id bits, decoded by the reader against
     * self-format.tsv) plus its file and memory sizes. Bounded by the read window and a
     * sane cap, and it says if it stopped short so a truncation never reads as "that is
     * all there was". */
    unsigned int cap = 64;
    unsigned int reported = 0;
    for (unsigned int i = 0; i < segment_count && i < cap; i++) {
        unsigned long long off = 0x20ull + (unsigned long long)i * 0x20ull;
        if (off + 0x20ull > (unsigned long long)got) {
            break;
        }
        char field[48];
        char idx[24];
        size_t d = obs_format_u64(idx, i);
        idx[d] = '\0';
        size_t k = obs_append(field, 0, sizeof field, "structure/segment/");
        k = obs_append(field, k, sizeof field, idx);
        obs_append(field, k, sizeof field, "/flags");
        obs_report_u64(field, obs_le(buf, (unsigned int)off, 8), "self_segment 0x00");
        k = obs_append(field, 0, sizeof field, "structure/segment/");
        k = obs_append(field, k, sizeof field, idx);
        obs_append(field, k, sizeof field, "/file_size");
        obs_report_u64(field, obs_le(buf, (unsigned int)off + 16, 8),
                       "self_segment 0x10");
        k = obs_append(field, 0, sizeof field, "structure/segment/");
        k = obs_append(field, k, sizeof field, idx);
        obs_append(field, k, sizeof field, "/memory_size");
        obs_report_u64(field, obs_le(buf, (unsigned int)off + 24, 8),
                       "self_segment 0x18");
        reported++;
    }
    if (reported < segment_count) {
        obs_report_sysinfo("structure/segment-table", "truncated",
                           "more segments than the read window or cap held");
    }

    /* ex_info at header_size-0x70, self-checked on ptype. On the previous generation it
     * and the 0x30-byte npdrm block close the header; if that holds here, ptype is one
     * of the known values and the four fields are reported. If not, the block is
     * declared not-located rather than guessed - the current-generation tail layout is
     * exactly what is unconfirmed. */
    if (header_size >= 0x70 && header_size <= (unsigned long long)got) {
        unsigned long long ex = header_size - 0x70;
        unsigned long long ptype = obs_le(buf, (unsigned int)ex + 8, 8);
        if (obs_ptype_is_known(ptype)) {
            obs_report_u64("structure/ex_info/paid", obs_le(buf, (unsigned int)ex, 8),
                           "ex_info 0x00");
            obs_report_u64("structure/ex_info/ptype", ptype, "ex_info 0x08");
            obs_report_u64("structure/ex_info/app_version",
                           obs_le(buf, (unsigned int)ex + 16, 8), "ex_info 0x10");
            obs_report_u64("structure/ex_info/fw_version",
                           obs_le(buf, (unsigned int)ex + 24, 8), "ex_info 0x18");
            /* npdrm follows ex_info. Type is format; the content id is the title's own,
             * so only that it is present and its length are reported. */
            unsigned long long np = header_size - 0x30;
            if (np + 0x30ull <= (unsigned long long)got) {
                obs_report_u64("structure/npdrm/type", obs_le(buf, (unsigned int)np, 2),
                               "npdrm_control 0x00");
                obs_report_sysinfo("structure/npdrm/content_id", "present",
                                   "19 bytes, value not reported");
            }
        } else {
            obs_report_sysinfo(
                "structure/ex_info", "not located",
                "header_size-0x70 gave no known ptype; tail layout may differ here");
        }
    } else {
        obs_report_sysinfo("structure/ex_info", "not located",
                           "header did not fit the read window");
    }

    /* The installed sce_sys tree of the same title: the file set a package carries, as
     * it lands on disk. Names only - the entry inventory a builder reproduces, not any
     * file's contents. `found` is `<dir>/eboot.bin`; replace the trailing name with
     * `sce_sys`. */
    char sysdir[1024];
    size_t fl = 0;
    while (found[fl]) {
        fl++;
    }
    while (fl > 0 && found[fl - 1] != '/') {
        fl--;
    }
    size_t s = obs_append_n(sysdir, 0, sizeof sysdir, found, fl);
    obs_append(sysdir, s, sizeof sysdir, "sce_sys");
    int sdir = sceKernelOpen(sysdir, OBS_O_RDONLY, 0);
    if (sdir >= 0) {
        char dents[4096];
        unsigned int files = 0;
        for (;;) {
            sce_ssize_t n = sceKernelGetdents(sdir, dents, (int)sizeof dents);
            if (n <= 0) {
                break;
            }
            long pos = 0;
            while (pos + OBS_DIRENT_NAME < n) {
                unsigned int reclen = (unsigned int)obs_le(
                    (const unsigned char *)dents + pos, OBS_DIRENT_RECLEN, 2);
                if (reclen == 0) {
                    break;
                }
                unsigned int namlen = (unsigned char)dents[pos + OBS_DIRENT_NAMLEN];
                const char *name = dents + pos + OBS_DIRENT_NAME;
                int dot = (namlen == 1 && name[0] == '.') ||
                          (namlen == 2 && name[0] == '.' && name[1] == '.');
                if (!dot && namlen > 0) {
                    char nm[256];
                    obs_append_n(nm, 0, sizeof nm, name, namlen);
                    obs_report_sysinfo("structure/sce_sys", "entry", nm);
                    files++;
                }
                pos += (long)reclen;
            }
        }
        sceKernelClose(sdir);
        obs_report_u64("structure/sce_sys/count", files, "installed sce_sys entries");
    }

    return obs_pass_value(segment_count);
}

static const obs_check selfaudit_checks[] = {
    {"048-selfaudit/confirm-table", "libkernel", "sceKernelGetdents", OBS_CAP_NONE,
     OBS_CAP_NONE, (const void *)&sceKernelGetdents, check_confirm_format_table,
     OBS_FROM_DERIVED},
    {"048-selfaudit/metadata-differential", "libkernel", "sceKernelGetdents",
     OBS_CAP_NONE, OBS_CAP_NONE, (const void *)&sceKernelGetdents,
     check_metadata_differential, OBS_FROM_DERIVED},
    {"048-selfaudit/container-structure", "libkernel", "sceKernelGetdents",
     OBS_CAP_NONE, OBS_CAP_NONE, (const void *)&sceKernelGetdents,
     check_container_structure, OBS_FROM_DERIVED},
};

const obs_section obs_section_selfaudit = {
    "048-selfaudit",
    "SELF format confirmation",
    "Finds a real container by walking the application directories and, on the "
    "console, confirms "
    "selfish's format table against it, reports the container's full measured "
    "structure (header, "
    "segment table, ex_info/npdrm) as raw values, and censuses the installed-title "
    "metadata "
    "population. Measurements a gen-5 package is built from - not the vendor's file "
    "contents.",
    selfaudit_checks,
    OBS_COUNT(selfaudit_checks),
};
