/* ---- 048-selfaudit ---------------------------------------------------------
 *
 * Confirm selfish's SELF format table against a real current-generation container, on
 * the console, reporting only the verdict.
 *
 * # It finds the container, it is not told where one is
 *
 * An earlier version named specific title ids - `/system/vsh/app/NPXS40112/eboot.bin`
 * and a couple of siblings. That was wrong twice over: it only ever checked containers
 * somebody had written down, and a firmware that shuffled its title ids would find
 * nothing. This walks the application directories with `sceKernelGetdents` and audits
 * the first real container it finds. The only paths named here are the **structural
 * roots** where applications live, the way `/bin` is where programs live - not any
 * particular title. (selfish#D087)
 *
 * # What replaced the dump, and why
 *
 * This began as a probe that copied a real SELF header off the box to a file, for
 * `selfish audit` to read on a dev machine. That carried the vendor header's bytes off
 * the console - the extract-and-read-offline side of the provenance line. This reads
 * the header transiently *here*, compares it against the values selfish's format table
 * pins, and reports which the current generation keeps. The header bytes never land in
 * a file and never leave the box; only the finding does. (selfish#D086)
 *
 * # Where the expected values come from
 *
 * `include/obscene/self_header.gen.h`, generated by `obscene-tool selfheader` from
 * selfish's `data/self-format.tsv` and `selfish-abi`. Not a second copy of the table -
 * a projection of the one table into C, regenerated from it, drift-gated by
 * `verify.sh`. The magics recognise that a file *is* a SELF while scanning; the fixed
 * rows are what a match confirms; the magic is excluded from the confirm rows because
 * it identifies the generation rather than being a row a newer file should match.
 *
 * # Vendor container versus our own
 *
 * A container found under a system or user application root is the vendor's, which is
 * the point.
 * `/app0` is the *running app's own* eboot - a real vendor container when obSCEne runs
 * as a payload inside a hijacked app, but obSCEne's own fake SELF when it runs as a
 * standalone package. So the roots are scanned first and `/app0` is the last resort,
 * and the verdict says which it read, so a self-check is never mistaken for a vendor
 * confirmation.
 *
 * # What it reports on a difference
 *
 * A matching row reveals nothing not already public. A row that differs is a finding,
 * and the measured value is reported with it, because "flags differs" without the value
 * is not actionable - a format constant the probe observed, reported the way it reports
 * every syscall return, not a meaning read off the bytes. What a difference *means* at
 * the new generation still needs a citable source (selfish principle 1); the probe
 * states the difference and stops.
 */

#include "obscene/harness.h"
#include "obscene/platform.h"
#include "obscene/report.h"
#include "obscene/runtime.h"
#include "obscene/sections.h"
#include "obscene/self_header.gen.h"
#include "obscene/status.h"

/* Enough of the header to cover every fixed row. self_header is 0x20 bytes; a little
 * more costs nothing and future rows past 0x20 would be covered too. */
#define OBS_SELFAUDIT_LEN 0x40
#define OBS_SELF_STRUCT_LEN 4096u

/* The structural roots where applications live. Not title ids - the directories a title
 * id sits *inside*. The walk discovers whatever is there. A system app is the vendor
 * container the audit wants; `/app0` is the running app itself and is tried last (see
 * the header comment). */
static const char *const obs_app_roots[] = {
    "/system_ex/app",
    "/system/vsh/app",
    "/user/app",
};
/* Read a little-endian value of `size` bytes at `offset`. */
static unsigned long long obs_le(const unsigned char *buf, unsigned int offset,
                                 unsigned int size) {
    unsigned long long value = 0;
    for (unsigned int i = 0; i < size; i++) {
        value |= (unsigned long long)buf[offset + i] << (i * 8u);
    }
    return value;
}

static long obs_read_header(const char *path, unsigned char *buf, size_t cap) {
    if (cap == 0) {
        return -1;
    }
    int fd = sceKernelOpen(path, OBS_O_RDONLY, 0);
    if (fd < 0) {
        return -1;
    }
    long total = 0;
    while (total < (long)cap) {
        sce_ssize_t n = sceKernelRead(fd, buf + total, (size_t)((long)cap - total));
        if (n < 0) {
            sceKernelClose(fd);
            return -1;
        }
        if (n == 0) {
            break;
        }
        total += (long)n;
    }
    sceKernelClose(fd);
    return total;
}

static int obs_is_self(const unsigned char *buf) {
    unsigned long long magic = obs_le(buf, 0, 4);
    for (unsigned int i = 0; i < OBS_COUNT(obs_self_magics); i++) {
        if (magic == obs_self_magics[i]) {
            return 1;
        }
    }
    return 0;
}

static size_t obs_append(char *dst, size_t k, size_t cap, const char *b) {
    while (*b && k < cap - 1) {
        dst[k++] = *b++;
    }
    dst[k] = '\0';
    return k;
}

static size_t obs_append_n(char *dst, size_t k, size_t cap, const char *b, size_t n) {
    for (size_t i = 0; i < n && k < cap - 1; i++) {
        dst[k++] = b[i];
    }
    dst[k] = '\0';
    return k;
}

#define OBS_APP0_EBOOT "/app0/eboot.bin"

/* Report one measured u64 field as a hex value under `field`. `note` says where it was
 * read. */
static void obs_report_u64(const char *field, unsigned long long value,
                           const char *note) {
    char text[24];
    size_t n = obs_format_hex(text, value);
    text[n] = '\0';
    obs_report_sysinfo(field, text, note);
}

typedef struct {
    const char *origin;
    const char *path;
} obs_audit_candidate_t;

static const obs_audit_candidate_t obs_audit_candidates[] = {
    {"vendor", "/system_ex/app/PPSA02664/eboot.bin"},
    {"vendor", "/system_ex/app/PPSA04263/eboot.bin"},
    {"vendor", "/system_ex/app/PPSA03416/eboot.bin"},
    {"vendor", "/system/vsh/app/NPXS40038/eboot.bin"},
    {"fake", "/system_ex/app/FAKE00000/eboot.bin"},
    {"vendor", "/system_ex/app/PPSA28061/eboot.bin"},
    {"vendor", "/system_ex/app/PPSA25872/eboot.bin"},
    {"vendor", "/system_ex/app/PPSA21564/eboot.bin"},
    {"fake", "/user/app/FAKE00000/eboot.bin"},
    {"vendor", "/user/app/PPSA03416/eboot.bin"},
    {"vendor", "/system/vsh/app/NPXS40112/eboot.bin"},
};

typedef struct {
    char origin[32];
    char path[256];
} obs_found_container_t;

#define OBS_MAX_CONTAINERS 32

static int obs_locate_containers(obs_found_container_t *out, int max_count) {
    int count = 0;
    unsigned char test_buf[OBS_SELFAUDIT_LEN];

    /* 1. Try known candidate targets first */
    for (size_t c = 0; c < OBS_COUNT(obs_audit_candidates) && count < max_count; c++) {
        const char *p = obs_audit_candidates[c].path;
        if (obs_read_header(p, test_buf, sizeof(test_buf)) >= (long)sizeof(test_buf) &&
            obs_is_self(test_buf)) {
            int dup = 0;
            for (int j = 0; j < count; j++) {
                if (obs_strcmp(out[j].path, p) == 0) {
                    dup = 1;
                    break;
                }
            }
            if (!dup) {
                obs_append(out[count].origin, 0, sizeof(out[count].origin), obs_audit_candidates[c].origin);
                obs_append(out[count].path, 0, sizeof(out[count].path), p);
                count++;
            }
        }
    }

    /* 2. Walk structural roots if we have room */
    for (size_t r = 0; r < OBS_COUNT(obs_app_roots) && count < max_count; r++) {
        const char *root = obs_app_roots[r];
        int dir = sceKernelOpen(root, OBS_O_RDONLY, 0);
        if (dir < 0) continue;

        char dents[4096];
        for (;;) {
            sce_ssize_t n = sceKernelGetdents(dir, dents, (int)sizeof dents);
            if (n <= 0) break;
            long pos = 0;
            while (pos + OBS_DIRENT_NAME < n && count < max_count) {
                unsigned int reclen = (unsigned int)obs_le(
                    (const unsigned char *)dents + pos, OBS_DIRENT_RECLEN, 2);
                if (reclen == 0) break;
                unsigned char type = (unsigned char)dents[pos + OBS_DIRENT_TYPE];
                unsigned int namlen = (unsigned char)dents[pos + OBS_DIRENT_NAMLEN];
                const char *name = dents + pos + OBS_DIRENT_NAME;
                int dot = (namlen == 1 && name[0] == '.') ||
                          (namlen == 2 && name[0] == '.' && name[1] == '.');
                if (type == OBS_DT_DIR && !dot && namlen > 0) {
                    char candidate[1024];
                    size_t k = obs_append(candidate, 0, sizeof(candidate), root);
                    k = obs_append(candidate, k, sizeof(candidate), "/");
                    k = obs_append_n(candidate, k, sizeof(candidate), name, namlen);
                    obs_append(candidate, k, sizeof(candidate), "/eboot.bin");
                    if (obs_read_header(candidate, test_buf, sizeof(test_buf)) >= (long)sizeof(test_buf) &&
                        obs_is_self(test_buf)) {
                        int dup = 0;
                        for (int j = 0; j < count; j++) {
                            if (obs_strcmp(out[j].path, candidate) == 0) {
                                dup = 1;
                                break;
                            }
                        }
                        if (!dup) {
                            obs_append(out[count].origin, 0, sizeof(out[count].origin), "vendor");
                            obs_append(out[count].path, 0, sizeof(out[count].path), candidate);
                            count++;
                        }
                    }
                }
                pos += (long)reclen;
            }
        }
        sceKernelClose(dir);
    }

    /* 3. Fallback to /app0 if nothing was found */
    if (count == 0) {
        char app0[64];
        obs_append(app0, 0, sizeof(app0), OBS_APP0_EBOOT);
        if (obs_read_header(app0, test_buf, sizeof(test_buf)) >= (long)sizeof(test_buf) &&
            obs_is_self(test_buf)) {
            obs_append(out[count].origin, 0, sizeof(out[count].origin), "own app");
            obs_append(out[count].path, 0, sizeof(out[count].path), app0);
            count++;
        }
    }

    return count;
}

static void obs_extract_title_id(const char *path, char *out, size_t out_sz) {
    if (path == NULL || out == NULL || out_sz == 0) {
        return;
    }
    out[0] = '\0';
    size_t len = obs_strlen(path);
    const char *suffix = "/eboot.bin";
    size_t s_len = obs_strlen(suffix);
    size_t end = len;
    if (len >= s_len && obs_strcmp(path + len - s_len, suffix) == 0) {
        end = len - s_len;
    }
    size_t start = end;
    while (start > 0 && path[start - 1] != '/') {
        start--;
    }
    size_t title_len = end - start;
    if (title_len > 0 && title_len < out_sz) {
        for (size_t i = 0; i < title_len; i++) {
            out[i] = path[start + i];
        }
        out[title_len] = '\0';
    } else {
        obs_append(out, 0, out_sz, "app");
    }
}

static obs_result check_confirm_format_table(void) {
    OBS_REQUIRE(&sceKernelOpen);
    OBS_REQUIRE(&sceKernelClose);
    OBS_REQUIRE(&sceKernelRead);
    OBS_REQUIRE(&sceKernelGetdents);

    static obs_found_container_t found[OBS_MAX_CONTAINERS];
    int count = obs_locate_containers(found, OBS_MAX_CONTAINERS);

    if (count == 0) {
        return obs_skip("no SELF container was reachable from this process");
    }

    static unsigned char buf[OBS_SELF_STRUCT_LEN];
    unsigned int rows = (unsigned int)(sizeof(obs_self_fields) / sizeof(obs_self_fields[0]));
    unsigned int total_matched = 0;
    unsigned int total_diverged = 0;
    unsigned int total_nonfake = 0;
    unsigned int ptype0_gen5 = 0;
    unsigned int ptype0_gen4 = 0;
    unsigned int ptype1_gen5 = 0;
    unsigned int ptype1_gen4 = 0;

    for (int c = 0; c < count; c++) {
        long got = obs_read_header(found[c].path, buf, sizeof(buf));
        if (got < (long)OBS_SELFAUDIT_LEN || !obs_is_self(buf)) {
            continue;
        }

        char title_id[32];
        obs_extract_title_id(found[c].path, title_id, sizeof title_id);

        obs_report_sysinfo("selfaudit/source", found[c].origin, found[c].path);

        /* 0. Report magic per container */
        unsigned long long magic = obs_le(buf, 0x00, 4);
        char magic_field[128];
        size_t mf = obs_append(magic_field, 0, sizeof magic_field, "selfaudit/");
        mf = obs_append(magic_field, mf, sizeof magic_field, title_id);
        obs_append(magic_field, mf, sizeof magic_field, "/magic");
        obs_report_u64(magic_field, magic, "self_header 0x00");

        /* 1. Read and report ex_info/ptype FIRST */
        unsigned long long header_size = obs_le(buf, 0x0C, 2);
        unsigned long long ptype = 0xffffffffffffffffULL;
        int has_ptype = 0;
        if (header_size >= 0x70 && header_size <= (unsigned long long)got) {
            unsigned long long ex = header_size - 0x70;
            ptype = obs_le(buf, (unsigned int)ex + 8, 8);
            has_ptype = 1;

            char ptype_field[128];
            size_t pf = obs_append(ptype_field, 0, sizeof ptype_field, "selfaudit/");
            pf = obs_append(ptype_field, pf, sizeof ptype_field, title_id);
            obs_append(ptype_field, pf, sizeof ptype_field, "/ex_info/ptype");
            obs_report_u64(ptype_field, ptype, "ex_info 0x08");

            if (ptype != 0x1) {
                total_nonfake++;
            }
            if (ptype == 0x0) {
                if (magic == 0xeef51454ull) {
                    ptype0_gen5++;
                } else if (magic == 0x1d3d154full) {
                    ptype0_gen4++;
                }
            } else if (ptype == 0x1) {
                if (magic == 0xeef51454ull) {
                    ptype1_gen5++;
                } else if (magic == 0x1d3d154full) {
                    ptype1_gen4++;
                }
            }
        } else {
            char ptype_field[128];
            size_t pf = obs_append(ptype_field, 0, sizeof ptype_field, "selfaudit/");
            pf = obs_append(ptype_field, pf, sizeof ptype_field, title_id);
            obs_append(ptype_field, pf, sizeof ptype_field, "/ex_info/ptype");
            obs_report_sysinfo(ptype_field, "not located", "header truncated or < 0x70");
        }

        unsigned int matched = 0;
        for (unsigned int i = 0; i < rows; i++) {
            const obs_self_field *row = &obs_self_fields[i];
            unsigned long long value = obs_le(buf, row->offset, row->size);
            char text[64];
            size_t n = obs_format_hex(text, value);
            text[n] = '\0';

            char field[128];
            size_t k = obs_append(field, 0, sizeof field, "selfaudit/");
            k = obs_append(field, k, sizeof field, title_id);
            k = obs_append(field, k, sizeof field, "/");
            obs_append(field, k, sizeof field, row->field);

            if (value == row->expected) {
                matched++;
                obs_report_sysinfo(field, "matches", text);
            } else {
                char want[OBS_NUM_MAX];
                size_t w = obs_format_hex(want, row->expected);
                want[w] = '\0';
                n = obs_append(text, n, sizeof text, " (table: ");
                n = obs_append(text, n, sizeof text, want);
                obs_append(text, n, sizeof text, ")");
                obs_report_sysinfo(field, "differs", text);
            }
        }

        unsigned long long segment_count = obs_le(buf, 0x18, 2);
        char seg_field[128];
        size_t sf = obs_append(seg_field, 0, sizeof seg_field, "structure/");
        sf = obs_append(seg_field, sf, sizeof seg_field, title_id);
        obs_append(seg_field, sf, sizeof seg_field, "/segment_count");
        obs_report_u64(seg_field, segment_count, "self_header 0x18");

        char verdict_field[128];
        size_t vf = obs_append(verdict_field, 0, sizeof verdict_field, "selfaudit/");
        vf = obs_append(verdict_field, vf, sizeof verdict_field, title_id);
        obs_append(verdict_field, vf, sizeof verdict_field, "/verdict");

        char verdict_detail[128];
        if (has_ptype) {
            char ptype_str[32];
            size_t pn = obs_format_hex(ptype_str, ptype);
            ptype_str[pn] = '\0';
            size_t vd = obs_append(verdict_detail, 0, sizeof verdict_detail, "ptype=");
            vd = obs_append(verdict_detail, vd, sizeof verdict_detail, ptype_str);
            if (matched == rows) {
                total_matched++;
                obs_append(verdict_detail, vd, sizeof verdict_detail, "; all fixed header rows match selfish table");
                obs_report_sysinfo(verdict_field, "confirmed", verdict_detail);
            } else {
                total_diverged++;
                obs_append(verdict_detail, vd, sizeof verdict_detail, "; some fixed rows differ");
                obs_report_sysinfo(verdict_field, "diverged", verdict_detail);
            }
        } else {
            if (matched == rows) {
                total_matched++;
                obs_report_sysinfo(verdict_field, "confirmed", "ptype=unknown; all fixed header rows match selfish table");
            } else {
                total_diverged++;
                obs_report_sysinfo(verdict_field, "diverged", "ptype=unknown; some fixed rows differ");
            }
        }
    }

    char nonfake_buf[32];
    size_t nb = obs_format_u64(nonfake_buf, total_nonfake);
    nonfake_buf[nb] = '\0';
    obs_report_sysinfo("selfaudit/nonfake_census", nonfake_buf,
                       total_nonfake > 0 ? "containers with ptype != 0x1 audited"
                                         : "no container with ptype != 0x1 found on console");

    char cbuf[32];
    size_t cl = obs_format_u64(cbuf, ptype0_gen5);
    cbuf[cl] = '\0';
    obs_report_sysinfo("selfaudit/cross_census/ptype0_gen5", cbuf,
                       "genuine (ptype 0x0) with gen-5 magic (0xeef51454)");

    cl = obs_format_u64(cbuf, ptype0_gen4);
    cbuf[cl] = '\0';
    obs_report_sysinfo("selfaudit/cross_census/ptype0_gen4", cbuf,
                       "genuine (ptype 0x0) with gen-4 magic (0x1d3d154f)");

    cl = obs_format_u64(cbuf, ptype1_gen5);
    cbuf[cl] = '\0';
    obs_report_sysinfo("selfaudit/cross_census/ptype1_gen5", cbuf,
                       "fake (ptype 0x1) with gen-5 magic (0xeef51454)");

    cl = obs_format_u64(cbuf, ptype1_gen4);
    cbuf[cl] = '\0';
    obs_report_sysinfo("selfaudit/cross_census/ptype1_gen4", cbuf,
                       "fake (ptype 0x1) with gen-4 magic (0x1d3d154f)");

    if (total_diverged == 0 && total_matched > 0) {
        return obs_pass_value(total_matched);
    }
    return obs_partial_value("audit completed on multiple containers; divergences noted", (uint64_t)count);
}

static obs_result check_metadata_differential(void) {
    OBS_REQUIRE(&sceKernelOpen);
    OBS_REQUIRE(&sceKernelClose);
    OBS_REQUIRE(&sceKernelRead);
    OBS_REQUIRE(&sceKernelGetdents);

    unsigned int ps5_titles = 0;
    unsigned int ps4_titles = 0;
    unsigned int gen5_containers = 0;
    unsigned int gen4_containers = 0;

    /* 1. Inspect running application container in /app0 */
    unsigned char app0_hdr[32];
    if (obs_read_header("/app0/sce_sys/param.json", app0_hdr, sizeof app0_hdr) > 0 &&
        app0_hdr[0] == '{') {
        ps5_titles++;
    } else if (obs_read_header("/app0/sce_sys/param.sfo", app0_hdr, sizeof app0_hdr) >=
                   4 &&
               app0_hdr[0] == 0x00 && app0_hdr[1] == 'P' && app0_hdr[2] == 'S' &&
               app0_hdr[3] == 'F') {
        ps4_titles++;
    }
    if (obs_read_header("/app0/eboot.bin", app0_hdr, sizeof app0_hdr) >= 4) {
        unsigned long long magic = obs_le(app0_hdr, 0, 4);
        if (magic == obs_self_magics[0]) {
            gen5_containers++;
        } else if (magic == obs_self_magics[1]) {
            gen4_containers++;
        }
    }

    /* 2. Walk application directory roots if accessible */
    for (unsigned int r = 0; r < OBS_COUNT(obs_app_roots); r++) {
        const char *root = obs_app_roots[r];
        int dir = sceKernelOpen(root, OBS_O_RDONLY, 0);
        if (dir < 0) {
            continue;
        }
        char dents[4096];
        for (;;) {
            sce_ssize_t n = sceKernelGetdents(dir, dents, (int)sizeof dents);
            if (n <= 0) {
                break;
            }
            long pos = 0;
            while (pos + OBS_DIRENT_NAME < n) {
                unsigned int reclen = (unsigned int)obs_le(
                    (const unsigned char *)dents + pos, OBS_DIRENT_RECLEN, 2);
                if (reclen == 0) {
                    break;
                }
                unsigned char type = (unsigned char)dents[pos + OBS_DIRENT_TYPE];
                unsigned int namlen = (unsigned char)dents[pos + OBS_DIRENT_NAMLEN];
                const char *name = dents + pos + OBS_DIRENT_NAME;
                int dot = (namlen == 1 && name[0] == '.') ||
                          (namlen == 2 && name[0] == '.' && name[1] == '.');
                if (type == OBS_DT_DIR && !dot && namlen > 0) {
                    char path[1024];
                    unsigned char header[32];

                    /* Check sce_sys/param.json */
                    size_t k = obs_append(path, 0, sizeof path, root);
                    k = obs_append(path, k, sizeof path, "/");
                    k = obs_append_n(path, k, sizeof path, name, namlen);
                    obs_append(path, k, sizeof path, "/sce_sys/param.json");
                    if (obs_read_header(path, header, sizeof header) > 0 &&
                        header[0] == '{') {
                        ps5_titles++;
                    }

                    /* Check sce_sys/param.sfo */
                    k = obs_append(path, 0, sizeof path, root);
                    k = obs_append(path, k, sizeof path, "/");
                    k = obs_append_n(path, k, sizeof path, name, namlen);
                    obs_append(path, k, sizeof path, "/sce_sys/param.sfo");
                    if (obs_read_header(path, header, sizeof header) >= 4 &&
                        header[0] == 0x00 && header[1] == 'P' && header[2] == 'S' &&
                        header[3] == 'F') {
                        ps4_titles++;
                    }

                    /* Check eboot.bin container magic */
                    k = obs_append(path, 0, sizeof path, root);
                    k = obs_append(path, k, sizeof path, "/");
                    k = obs_append_n(path, k, sizeof path, name, namlen);
                    obs_append(path, k, sizeof path, "/eboot.bin");
                    if (obs_read_header(path, header, sizeof header) >= 4) {
                        unsigned long long magic = obs_le(header, 0, 4);
                        if (magic == obs_self_magics[0]) {
                            gen5_containers++;
                        } else if (magic == obs_self_magics[1]) {
                            gen4_containers++;
                        }
                    }
                }
                pos += (long)reclen;
            }
        }
        sceKernelClose(dir);
    }

    char count_buf[OBS_NUM_MAX];
    size_t l = obs_format_u64(count_buf, ps5_titles);
    count_buf[l] = '\0';
    obs_report_sysinfo("metadata/ps5_param_json", count_buf,
                       "installed titles declaring param.json");

    l = obs_format_u64(count_buf, ps4_titles);
    count_buf[l] = '\0';
    obs_report_sysinfo("metadata/ps4_param_sfo", count_buf,
                       "installed titles declaring param.sfo");

    l = obs_format_u64(count_buf, gen5_containers);
    count_buf[l] = '\0';
    obs_report_sysinfo("metadata/gen5_containers", count_buf,
                       "eboot containers with gen-5 magic (54 14 F5 EE)");

    l = obs_format_u64(count_buf, gen4_containers);
    count_buf[l] = '\0';
    obs_report_sysinfo("metadata/gen4_containers", count_buf,
                       "eboot containers with gen-4 magic (4F 15 3D 1D)");

    if (ps5_titles > 0 && ps4_titles == 0) {
        obs_report_sysinfo("metadata/verdict", "ps5_native_only",
                           "all inspected titles are native PS5");
        return obs_pass_value(ps5_titles);
    }
    if (ps5_titles > 0 && ps4_titles > 0) {
        obs_report_sysinfo("metadata/verdict", "mixed",
                           "both native PS5 and PS4 compat titles found");
        return obs_pass_value(ps5_titles + ps4_titles);
    }
    if (ps4_titles > 0) {
        obs_report_sysinfo("metadata/verdict", "ps4_compat_only",
                           "only PS4 compat titles discovered");
        return obs_pass_value(ps4_titles);
    }

    obs_report_sysinfo("metadata/verdict", "none",
                       "no installed title metadata was reachable");
    return obs_partial("no installed title metadata reachable");
}

/* ---- 048-selfaudit/container-structure
 * --------------------------------------------------------
 *
 * The container's whole measured shape, so selfish has the numbers a gen-5 package is
 * built from.
 *
 * `confirm-table` answers "do the nine fixed header constants still hold". This answers
 * "what does the rest of a real container actually contain" - the header's per-file
 * fields, the segment table, and the ex_info/npdrm blocks - as **raw measured values**.
 * It does not decode them: what a segment flag bit or an ex_info ptype value *means*
 * lives in selfish's self-format.tsv, and re-encoding that here would be a second copy
 * of a judgement that must have one home. So the report carries the number; the reader
 * turns it back into meaning against that table.
 *
 * Two provenance points, both load-bearing:
 *
 *  - The structural offsets used here (header_size at 0x0C, the segment table at 0x20
 * with a 0x20 stride, ex_info at header_size-0x70, npdrm at header_size-0x30) are
 * format facts from selfish's table, cited but not yet *projected* the way the nine
 * fixed rows are through self_header.gen.h. Promoting them into the generated header -
 * so they cannot drift from the table - is a follow-up, blocked only on the
 * generator/selfish rescaffold settling. (D286)
 *
 *  - ex_info and npdrm sit at the tail of the header on the previous generation.
 * Whether that layout holds at the current generation is exactly what is unconfirmed,
 * so the ex_info read is self-checked: if ptype is not one of the small values the
 * format admits, the block is reported as "not located" rather than as four numbers
 * that might be the wrong bytes. Principle 2 - a wrong value that reads as a finding
 * costs more than a withheld one.
 *
 * The content id inside npdrm is a title's own identifier; its presence and length are
 * format and are reported, its value is the vendor title's and is not.
 */

/* A larger window than confirm-table's 0x40: enough for the header (self_header +
 * segment table + ELF phdrs + ex_info + npdrm), which for an ordinary title is well
 * under 4 KiB. Reads are bounded by whatever was actually returned, so a short read
 * simply reports fewer fields. */

static obs_result check_container_structure(void) {
    OBS_REQUIRE(&sceKernelOpen);
    OBS_REQUIRE(&sceKernelClose);
    OBS_REQUIRE(&sceKernelRead);
    OBS_REQUIRE(&sceKernelGetdents);

    static obs_found_container_t found[OBS_MAX_CONTAINERS];
    int count = obs_locate_containers(found, OBS_MAX_CONTAINERS);

    if (count == 0) {
        return obs_skip("no SELF container was reachable from this process");
    }

    static unsigned char buf[OBS_SELF_STRUCT_LEN];
    unsigned long long total_segments = 0;

    for (int c = 0; c < count; c++) {
        long got = obs_read_header(found[c].path, buf, sizeof(buf));
        if (got < 4 || !obs_is_self(buf)) {
            continue;
        }

        char title_id[32];
        obs_extract_title_id(found[c].path, title_id, sizeof title_id);

        char key_prefix[64];
        size_t kp = obs_append(key_prefix, 0, sizeof key_prefix, "structure/");
        kp = obs_append(key_prefix, kp, sizeof key_prefix, title_id);
        obs_append(key_prefix, kp, sizeof key_prefix, "/");

        obs_report_sysinfo("structure/source", found[c].origin, found[c].path);

        unsigned long long magic = obs_le(buf, 0x00, 4);
        unsigned long long header_size = obs_le(buf, 0x0C, 2);
        unsigned long long meta_size = obs_le(buf, 0x0E, 2);
        unsigned long long file_size = obs_le(buf, 0x10, 8);
        unsigned long long segment_count = obs_le(buf, 0x18, 2);
        total_segments += segment_count;

        char field[128];
        size_t k = obs_append(field, 0, sizeof field, key_prefix);
        obs_append(field, k, sizeof field, "magic");
        obs_report_u64(field, magic, "self_header 0x00");

        k = obs_append(field, 0, sizeof field, key_prefix);
        obs_append(field, k, sizeof field, "header_size");
        obs_report_u64(field, header_size, "self_header 0x0C");

        k = obs_append(field, 0, sizeof field, key_prefix);
        obs_append(field, k, sizeof field, "meta_size");
        obs_report_u64(field, meta_size, "self_header 0x0E");

        k = obs_append(field, 0, sizeof field, key_prefix);
        obs_append(field, k, sizeof field, "file_size");
        obs_report_u64(field, file_size, "self_header 0x10");

        k = obs_append(field, 0, sizeof field, key_prefix);
        obs_append(field, k, sizeof field, "segment_count");
        obs_report_u64(field, segment_count, "self_header 0x18");

        unsigned int cap = 64;
        unsigned int reported = 0;
        for (unsigned int i = 0; i < segment_count && i < cap; i++) {
            unsigned long long off = 0x20ull + (unsigned long long)i * 0x20ull;
            if (off + 0x20ull > (unsigned long long)got) {
                break;
            }
            char idx[24];
            size_t d = obs_format_u64(idx, i);
            idx[d] = '\0';
            k = obs_append(field, 0, sizeof field, key_prefix);
            k = obs_append(field, k, sizeof field, "segment/");
            k = obs_append(field, k, sizeof field, idx);
            obs_append(field, k, sizeof field, "/flags");
            obs_report_u64(field, obs_le(buf, (unsigned int)off, 8), "self_segment 0x00");

            k = obs_append(field, 0, sizeof field, key_prefix);
            k = obs_append(field, k, sizeof field, "segment/");
            k = obs_append(field, k, sizeof field, idx);
            obs_append(field, k, sizeof field, "/file_size");
            obs_report_u64(field, obs_le(buf, (unsigned int)off + 16, 8),
                           "self_segment 0x10");

            k = obs_append(field, 0, sizeof field, key_prefix);
            k = obs_append(field, k, sizeof field, "segment/");
            k = obs_append(field, k, sizeof field, idx);
            obs_append(field, k, sizeof field, "/memory_size");
            obs_report_u64(field, obs_le(buf, (unsigned int)off + 24, 8),
                           "self_segment 0x18");
            reported++;
        }
        if (reported < segment_count) {
            k = obs_append(field, 0, sizeof field, key_prefix);
            obs_append(field, k, sizeof field, "segment-table");
            obs_report_sysinfo(field, "truncated",
                               "more segments than the read window or cap held");
        }

        if (header_size >= 0x70 && header_size <= (unsigned long long)got) {
            unsigned long long ex = header_size - 0x70;
            unsigned long long ptype = obs_le(buf, (unsigned int)ex + 8, 8);

            k = obs_append(field, 0, sizeof field, key_prefix);
            obs_append(field, k, sizeof field, "ex_info/paid");
            obs_report_u64(field, obs_le(buf, (unsigned int)ex, 8),
                           "ex_info 0x00");

            k = obs_append(field, 0, sizeof field, key_prefix);
            obs_append(field, k, sizeof field, "ex_info/ptype");
            obs_report_u64(field, ptype, "ex_info 0x08");

            k = obs_append(field, 0, sizeof field, key_prefix);
            obs_append(field, k, sizeof field, "ex_info/app_version");
            obs_report_u64(field,
                           obs_le(buf, (unsigned int)ex + 16, 8), "ex_info 0x10");

            k = obs_append(field, 0, sizeof field, key_prefix);
            obs_append(field, k, sizeof field, "ex_info/fw_version");
            obs_report_u64(field,
                           obs_le(buf, (unsigned int)ex + 24, 8), "ex_info 0x18");

            unsigned long long np = header_size - 0x30;
            if (np + 0x30ull <= (unsigned long long)got) {
                k = obs_append(field, 0, sizeof field, key_prefix);
                obs_append(field, k, sizeof field, "npdrm/type");
                obs_report_u64(field, obs_le(buf, (unsigned int)np, 2),
                               "npdrm_control 0x00");

                k = obs_append(field, 0, sizeof field, key_prefix);
                obs_append(field, k, sizeof field, "npdrm/content_id");
                obs_report_sysinfo(field, "present",
                                   "19 bytes, value not reported");
            }
        } else {
            k = obs_append(field, 0, sizeof field, key_prefix);
            obs_append(field, k, sizeof field, "ex_info");
            obs_report_sysinfo(field, "not located",
                               "header did not fit the read window");
        }
    }

    return obs_pass_value(total_segments);
}

static const obs_check selfaudit_checks[] = {
    {"048-selfaudit/confirm-table", "libkernel", "sceKernelGetdents", OBS_CAP_NONE,
     OBS_CAP_NONE, (const void *)&sceKernelGetdents, check_confirm_format_table,
     OBS_FROM_DERIVED},
    {"048-selfaudit/metadata-differential", "libkernel", "sceKernelGetdents",
     OBS_CAP_NONE, OBS_CAP_NONE, (const void *)&sceKernelGetdents,
     check_metadata_differential, OBS_FROM_DERIVED},
    {"048-selfaudit/container-structure", "libkernel", "sceKernelGetdents",
     OBS_CAP_NONE, OBS_CAP_NONE, (const void *)&sceKernelGetdents,
     check_container_structure, OBS_FROM_DERIVED},
};

const obs_section obs_section_selfaudit = {
    "048-selfaudit",
    "SELF format confirmation",
    "Finds a real container by walking the application directories and, on the "
    "console, confirms "
    "selfish's format table against it, reports the container's full measured "
    "structure (header, "
    "segment table, ex_info/npdrm) as raw values, and censuses the installed-title "
    "metadata "
    "population. Measurements a gen-5 package is built from - not the vendor's file "
    "contents.",
    selfaudit_checks,
    OBS_COUNT(selfaudit_checks),
};
